### ISSUE TITLE
Publish the extension to Open VSX

### ISSUE THREAD

**Issue by cooperbenson-qz** [slackhq/vscode-hack#133]
Due to Microsoft's licensing restrictions on extensions distributed through the official repository, some tools require the use of [Open VSX](https://open-vsx.org/) instead. We're looking into a tool that needs to use Open VSX, and would love to see this extension published there. [Here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) are the docs for how to publish an extension there. Would love to help out however we can!

**Comment by muglug** [comment]
What Microsoft licensing restrictions are preventing you from using exensions through the official VS Code store?

**Comment by fredemmott** [comment]
AIUI Forks of VS Code are not able to use it; https://www.gitpod.io/blog/openvscode-server-launch was initially a major reason, though microsoft open-sourced their implementation shortly after (https://github.com/microsoft/vscode/commit/822f995357f725216cdee6e05f1f1552ccbbd882)

**Comment by cooperbenson-qz** [comment]
Exactly. In fact, GitPod is the exact reason we're looking into this. For the short term, we can probably just build a `.vsix` and host it on a publicly available URL, but long term it would be great if we could get official binaries and updates via Open VSX.

**Comment by PranayAgarwal** [comment]
Once upon a time we did publish the compiled VSIX as part of the Github release, but that build pipeline got messed up at some point. I can try and add a Github Action to enable that again, which should make this use case a lot smoother at least.

For the full ask, we'll need to get the registry (https://open-vsx.org/) and its publisher agreement looked at and approved. No promises or timeline to share on that from my side.

**Comment by cooperbenson-qz** [comment]
Yeah if you could add the `.vsix` as a release artifact that would be amazing!

**Comment by PranayAgarwal** [comment]
This is now working again! See https://github.com/slackhq/vscode-hack/releases/tag/v2.13.0, which was published automatically.

**Comment by filiptronicek** [comment]
Hey there everyone, since it seems a lot of users (including a lot of our users using Gitpod) use the extension, I would like to propose that the extension gets automatically published via the special repository Open VSX has setup for publishing third-party extensions, https://github.com/open-vsx/publish-extensions/ - although this should be only considered temporary before Slack can figure the legal side of it out 🙏.

If nobody from Slack has anything against it, I will add it to the repo.

cc @PranayAgarwal @muglug

**Comment by PranayAgarwal** [comment]
Hey @filiptronicek, I can't say if we will be able to take over ownership of the listing page on https://open-vsx.org/, but I also don't see any problems (legal or otherwise) with this above approach being the permanent one, as long as it meets the terms of the MIT license.

**Comment by filiptronicek** [comment]
If it wouldn't be possible for Slack to take over ownership, that's no problem as well. We try to have as few extensions as possible on https://github.com/open-vsx/publish-extensions/ (hard to maintain publishing of ~400 extensions), but the fact that `.vsix` files are published as Release asset here [[1](https://github.com/slackhq/vscode-hack/issues/133#issuecomment-1063755664)] makes it a lot easier for our script to publish it. 

I will try to publish the extension now and come back with the results.

**Comment by filiptronicek** [comment]
Happy to report all went well and `pranayagarwal.vscode-hack` is published to open-vsx.org 🎉 
- https://open-vsx.org/extension/pranayagarwal/vscode-hack
- https://github.com/open-vsx/publish-extensions/commit/450dc341da8f72f27e01a1ead60f01aefd644857

cc @PranayAgarwal @cooperbenson-qz
