### ISSUE TITLE
Add support for `.hack` files (requires syntax highlighting changes)

### ISSUE THREAD

**Issue by fredemmott** [slackhq/vscode-hack#35]
`.hack` files will not require - or allow - leading markup or `<?hh` lines - they're always strict.

See https://github.com/facebook/hhvm/pull/8421 for hack and hackc change, https://github.com/hhvm/vim-hack/pull/46 for a corresponding change to vim

These two files are equivalent:

# foo.php
```hack
<?hh // strict
function foo(): void {
}
```

# foo.hack

```hack
function foo(): void {
}
```

**Comment by PranayAgarwal** [comment]
Is there an equivalent change in the hack syntax file in atom-ide-hack?

**Comment by fredemmott** [comment]
There's unlikely to be one - that project probably should be archived. I believe that Atom-IDE is no longer maintained (in general, not specifically atom-ide-hack)

**Comment by PranayAgarwal** [comment]
I have been using https://github.com/hhvm/atom-ide-hack/blob/master/grammars/hack.cson (which was earlier part of Nuclide) as the definitive syntax file for Hack. If this is deprecated, then will Hack not be supported in Atom at all?

**Comment by fredemmott** [comment]
I think that depends on what happens to https://github.com/atom/atom-languageclient and the corresponding UI elements.

I don't plan to to support Atom if we're not able to support anything beyond syntax highlighting.
