### ISSUE TITLE
Prevents vscode-elixir-ls autocomplete

### ISSUE THREAD

**Issue by English3000** [slackhq/vscode-hack#37]
I installed your extension.

When I returned to a personal project which uses Elixir, I found the [autocomplete extension](https://github.com/JakeBecker/vscode-elixir-ls) was not working.

When I disabled your extension and reloaded, the Elixir extension worked again.

**Comment by PranayAgarwal** [comment]
I went through the Elixir extension but couldn't find anything in there that would conflict with this one..

Could you try:
- Open a file that autocomplete isn't working on, and check (1) the file extension and (2) what vscode detects the file type as (bottom right of the screen)
- Check the OUTPUT panel and from the drop-down on the right see if there are any relevant logs that correspond to Hack or Elixir

**Comment by English3000** [comment]
I just turned on my computer again, and when I did, my Elixir extension wasn't autocompleting.

I enabled Hack and reloaded, and it began autocompleting again--meaning the issue wasn't with your extension.
