### ISSUE TITLE
maintenance plans

### ISSUE THREAD

**Issue by juanfernandoe** [slackhq/vscode-hack#42]
Hi,

I know probably this is not the place for this question but I don't know where to ask.

So, will this plugin be maintained in the future?
will slack keep working with hacklang even though the end of the php support?

**Comment by PranayAgarwal** [comment]
Hi @juanfernandoe, yes on both counts. Slack is going to keep using Hack and HHVM, and both Slack and the HHVM team itself is committed to ensuring the best developer experience, which includes this extension.

You can follow the HHVM blog at https://hhvm.com/blog/ for all changes and future plans for the language.

**Comment by juanfernandoe** [comment]
Hi @PranayAgarwal, I appreciate your taking the time to answer my question.
