### ISSUE TITLE
Autocomplete falls back to vscode default

### ISSUE THREAD

**Issue by Lexidor** [slackhq/vscode-hack#43]
##### ClassnameFoo.hack
```
class ClassnameFoo{
    public function bar(): void{}
}
```
##### example.hack
```
function doSomething(ClassnameFoo $foo): void{
    $foo-> //autocomplete this
}
```
The suggestions on pressing ctrl+space at the arrow are: 'ClassnameFoo', 'doSomething', 'foo', 'function', and 'void'

### Expected result
`bar() //ClassnameFoo::bar(): void`

Commands ran within the integrated terminal: `hh_client`
Result from hh_client: `src/example.hack:2:11,11: A name or variable name is expected here. (Parsing[1002])`

### System info:
```
hhvm --version
HipHop VM 4.0.2 (rel)
Compiler: 1550605031_606999898
Repo schema: a46021ba5e51d676a396f711ef442e334fa9152a

hh_client --version
hh--4.0.2 Tue Feb 19 20:40:27 2019

vscode-hack
Name: Hack
Id: pranayagarwal.vscode-hack
Description: Hack language & HHVM debugger support for Visual Studio Code
Version: 1.2.1
Publisher: Pranay Agarwal
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=pranayagarwal.vscode-hack
```

**Comment by fredemmott** [comment]
This is probably https://github.com/facebook/hhvm/blob/293adbb7980cf6201de5142ca4ab2e08b5e5bd03/hphp/hack/src/server/ffpAutocompleteService.ml#L53 losing the extension, so the '.hack' special behavior is gone.

**Comment by Lexidor** [comment]
Quoting fredemmott: `The first thing the parser usually does is "Skip until you see <?"`

Since a dothack file does not have a <?, the parser just waits to the end of the file and concludes "well... not much of note here". Dotphp and dothh files do contain a <?, so autocomplete and similar services will be available in those files.

Closing the issue since the problem is not one of the vscode-hack extension.
