### ISSUE TITLE
Syntax highlighting breaks down when using `shape(...)`

### ISSUE THREAD

**Issue by lexidor** [slackhq/vscode-hack#58]
The following code does not highlight properly:
```HACK
function foo(int $arg): shape(...){
  return shape();
}
```
https://ibb.co/fnHZvdT

**Comment by tspence** [comment]
Believe this is now closed, see screenshot:

![Screenshot 2019-10-24 11 15 15](https://user-images.githubusercontent.com/1933486/67513385-8ffbbd80-f64f-11e9-8e26-8bb32a7bf422.png)
