### ISSUE TITLE
`shape(...)` declaration seems to break syntax highlighting. 

### ISSUE THREAD

**Issue by mansu** [slackhq/vscode-hack#70]
It seems that the shape annotation seems to break syntax highlighting in vscode-hack.

Adding `shape(...)` declaration to any function should repro it. Here is a screenshot with sample code.

<img width="692" alt="Screen Shot 2019-10-16 at 3 37 24 PM" src="https://user-images.githubusercontent.com/93836/66964271-f74fb700-f02a-11e9-9b01-59b54831c22b.png">

**Comment by lexidor** [comment]
Related issue #58

**Comment by tspence** [comment]
Related: https://github.com/slackhq/vscode-hack/pull/69 brings in the latest changes from the Facebook IDE team.  I think this may correct the issue.

**Comment by tspence** [comment]
This appears to be solved with the latest revision to the grammar:

![Screenshot 2019-10-17 10 39 25](https://user-images.githubusercontent.com/1933486/67033364-6fb98500-f0ca-11e9-965e-1f2f1dfaad96.png)
