### ISSUE TITLE
How to use hackfmt to format new .hack files in visual studio code

### ISSUE THREAD

**Issue by mrth2** [slackhq/vscode-hack#87]

**Comment by lexidor** [comment]
I don't have enough information to give you an answer, but I am very willing to help. Are you using hhvm 4.x? You can check this by executing `hhvm - -version`. Hhvm 3.x can't understand dot hack files. If you are using 4.x, do dot hack files get the right syntax highlighting? If no, check your file associations for dot hack files. If it is not one of these causes, could you give me some more information?

**Comment by mrth2** [comment]
Yes, i am using hhvm 4x and it get the right syntax highligting.

Hmm, i missed to add .hhconfig on the working directory. After added it, the .hack files can now be formatted using visual code studio default "format document".
