### ISSUE TITLE
Inject into text.html.markdown to support fenced code blocks

### ISSUE THREAD

**Issue by bolinfest** [slackhq/vscode-hack#99]
I have requested the same change to the TOML extension: https://github.com/bungcip/better-toml/issues/29.

If you want to use the Kotlin extension as an example, here are the relevant bits:

* https://github.com/mathiasfrohlich/vscode-kotlin/blob/090fe4cd054d6142d7eaefdb69c12d4b063a089e/syntaxes/codeblock.json
* https://github.com/mathiasfrohlich/vscode-kotlin/blob/090fe4cd054d6142d7eaefdb69c12d4b063a089e/package.json#L68-L77

**Comment by bolinfest** [comment]
https://github.com/slackhq/vscode-hack/pull/100 is the fix.

**Comment by tspence** [comment]
> #100 is the fix.

💯
